swagger: "2.0"
info:
  title: Task API
  version: "1.0.0"

basePath: /api
schemes:
  - http

tags:
  - name: Projects
    description: Project CRUD
  - name: Tasks
    description: Task CRUD per project + CSV Import/Export

paths:
  /projects:
    get:
      tags: [Projects]
      summary: List all projects
      produces: [application/json]
      responses:
        200:
          description: List of projects
          schema:
            type: array
            items:
              $ref: "#/definitions/Project"

    post:
      tags: [Projects]
      summary: Create a project
      consumes: [application/json]
      produces: [application/json]
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/CreateProjectRequest"
      responses:
        201:
          description: Project created
          schema:
            $ref: "#/definitions/Project"
        400:
          description: Invalid payload

  /projects/{project_id}:
    get:
      tags: [Projects]
      summary: Get project by id
      produces: [application/json]
      parameters:
        - in: path
          name: project_id
          required: true
          type: integer
      responses:
        200:
          description: One project
          schema:
            $ref: "#/definitions/Project"
        404:
          description: Not found

    put:
      tags: [Projects]
      summary: Rename/update project by id
      consumes: [application/json]
      produces: [application/json]
      parameters:
        - in: path
          name: project_id
          required: true
          type: integer
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/UpdateProjectRequest"
      responses:
        200:
          description: Updated project
          schema:
            $ref: "#/definitions/Project"
        400:
          description: Invalid payload
        404:
          description: Not found

    delete:
      tags: [Projects]
      summary: Delete project by id (deletes tasks too if cascade)
      parameters:
        - in: path
          name: project_id
          required: true
          type: integer
      responses:
        204:
          description: Deleted
        404:
          description: Not found

  /projects/{project_id}/tasks:
    get:
      tags: [Tasks]
      summary: List tasks for a project (search + pagination + sort)
      produces: [application/json]
      parameters:
        - in: path
          name: project_id
          required: true
          type: integer

        - in: query
          name: q
          type: string
          required: false
          description: Search query (matches task content; supports multi-word)

        - in: query
          name: page
          type: integer
          required: false
          default: 1
          minimum: 1

        - in: query
          name: per_page
          type: integer
          required: false
          default: 5
          minimum: 1
          maximum: 100

        - in: query
          name: sort
          type: string
          required: false
          enum: [asc, desc]
          default: desc
          description: Sort by created time (asc=first added, desc=newest first)

      responses:
        200:
          description: Paginated list of tasks for the project
          schema:
            $ref: "#/definitions/PaginatedProjectTasks"

    post:
      tags: [Tasks]
      summary: Create a task in a project
      consumes: [application/json]
      produces: [application/json]
      parameters:
        - in: path
          name: project_id
          required: true
          type: integer

        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/CreateTaskRequest"

      responses:
        201:
          description: Task created
          schema:
            $ref: "#/definitions/Task"
        400:
          description: Invalid payload
        404:
          description: Project not found

  /projects/{project_id}/tasks/{task_id}:
    get:
      tags: [Tasks]
      summary: Get a task by id (project-scoped)
      produces: [application/json]
      parameters:
        - in: path
          name: project_id
          required: true
          type: integer
        - in: path
          name: task_id
          required: true
          type: integer
      responses:
        200:
          description: One task
          schema:
            $ref: "#/definitions/Task"
        404:
          description: Not found

    put:
      tags: [Tasks]
      summary: Update a task by id (project-scoped)
      consumes: [application/json]
      produces: [application/json]
      parameters:
        - in: path
          name: project_id
          required: true
          type: integer
        - in: path
          name: task_id
          required: true
          type: integer
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/UpdateTaskRequest"
      responses:
        200:
          description: Updated task
          schema:
            $ref: "#/definitions/Task"
        400:
          description: Invalid payload
        404:
          description: Not found

    delete:
      tags: [Tasks]
      summary: Delete a task by id (project-scoped)
      parameters:
        - in: path
          name: project_id
          required: true
          type: integer
        - in: path
          name: task_id
          required: true
          type: integer
      responses:
        204:
          description: Deleted
        404:
          description: Not found

  /projects/{project_id}/tasks/import-csv:
    post:
      tags: [Tasks]
      summary: Import tasks from CSV into a project
      consumes: [multipart/form-data]
      produces: [application/json]
      parameters:
        - in: path
          name: project_id
          required: true
          type: integer

        - in: formData
          name: file
          type: file
          required: true
          description: "CSV file (header: content,completed OR single-column rows)"

      responses:
        200:
          description: Import summary
          schema:
            $ref: "#/definitions/ImportSummary"
        400:
          description: Bad request
        404:
          description: Project not found
        500:
          description: DB insert failed

  /projects/{project_id}/tasks/export-csv:
    get:
      tags: [Tasks]
      summary: Export tasks of a project to CSV
      produces: [text/csv]
      parameters:
        - in: path
          name: project_id
          required: true
          type: integer

        - in: query
          name: q
          type: string
          required: false
          description: Optional search filter before exporting

        - in: query
          name: page
          type: integer
          required: false
          default: 1
          minimum: 1
          description: Optional - export only one page (if your backend supports this)

        - in: query
          name: per_page
          type: integer
          required: false
          default: 5
          minimum: 1
          maximum: 100
          description: Optional - export only one page (if your backend supports this)

        - in: query
          name: sort
          type: string
          required: false
          enum: [asc, desc]
          default: desc

      responses:
        200:
          description: CSV file download
          schema:
            type: string

definitions:
  Project:
    type: object
    properties:
      id:
        type: integer
        example: 1
      name:
        type: string
        example: "My Project"
      created:
        type: string
        example: "2025-12-23T10:30:00"

  CreateProjectRequest:
    type: object
    required: [name]
    properties:
      name:
        type: string
        example: "New Project"

  UpdateProjectRequest:
    type: object
    required: [name]
    properties:
      name:
        type: string
        example: "Renamed Project"

  Task:
    type: object
    properties:
      id:
        type: integer
        example: 10
      content:
        type: string
        example: "Buy groceries"
      completed:
        type: integer
        example: 0
      created:
        type: string
        example: "2025-12-23T10:30:00"
      project_id:
        type: integer
        example: 1

  CreateTaskRequest:
    type: object
    required: [content]
    properties:
      content:
        type: string
        example: "Read system design notes"
      completed:
        type: integer
        default: 0
        example: 0

  UpdateTaskRequest:
    type: object
    properties:
      content:
        type: string
        example: "Updated task text"
      completed:
        type: integer
        example: 1

  PaginatedProjectTasks:
    type: object
    properties:
      project_id:
        type: integer
        example: 1
      q:
        type: string
        example: "groceries"
      sort:
        type: string
        example: "desc"
      page:
        type: integer
        example: 1
      per_page:
        type: integer
        example: 5
      total:
        type: integer
        example: 100
      pages:
        type: integer
        example: 20
      has_next:
        type: boolean
        example: true
      has_prev:
        type: boolean
        example: false
      items:
        type: array
        items:
          $ref: "#/definitions/Task"

  ImportSummary:
    type: object
    properties:
      inserted:
        type: integer
        example: 10
      skipped:
        type: integer
        example: 2
      errors:
        type: integer
        example: 0
